"""empty message

Revision ID: 093863b5eb82
Revises: b4984e85b49b
Create Date: 2025-04-05 22:46:06.946521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093863b5eb82'
down_revision = 'b4984e85b49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connected_objects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conso_min', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('conso_max', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('conso_actuelle', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connected_objects', schema=None) as batch_op:
        batch_op.drop_column('conso_actuelle')
        batch_op.drop_column('conso_max')
        batch_op.drop_column('conso_min')

    # ### end Alembic commands ###
