"""empty message

Revision ID: 162ba08dd547
Revises: b4687373e081
Create Date: 2025-04-09 23:11:21.059948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '162ba08dd547'
down_revision = 'b4687373e081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('houses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Join_method', sa.String(length=20), nullable=True))
        batch_op.drop_column('Join')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('houses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Join', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('Join_method')

    # ### end Alembic commands ###
