"""empty message

Revision ID: 3d15e00bb93a
Revises: 53739e67c883
Create Date: 2025-04-05 21:29:33.496236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d15e00bb93a'
down_revision = '53739e67c883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nbAU', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nbDU', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('nbDU')
        batch_op.drop_column('nbAU')

    # ### end Alembic commands ###
