"""empty message

Revision ID: 497997748ca6
Revises: 1363b0ad635f
Create Date: 2025-04-10 16:36:40.662093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497997748ca6'
down_revision = '1363b0ad635f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('prénom', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('prénom')
        batch_op.drop_column('nom')

    # ### end Alembic commands ###
