"""empty message

Revision ID: 87f7bcc2a751
Revises: 497997748ca6
Create Date: 2025-04-14 18:09:15.369930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f7bcc2a751'
down_revision = '497997748ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connected_objects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gaz_min', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('gaz_max', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('gaz_actuelle', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gaz_visé', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('eau_min', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('eau_max', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('eau_actuelle', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('eau_visé', sa.Integer(), nullable=True))

    with op.batch_alter_table('object_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consumes_electricity', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('consumes_gas', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('consumes_water', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('other_consumption', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('object_types', schema=None) as batch_op:
        batch_op.drop_column('other_consumption')
        batch_op.drop_column('consumes_water')
        batch_op.drop_column('consumes_gas')
        batch_op.drop_column('consumes_electricity')

    with op.batch_alter_table('connected_objects', schema=None) as batch_op:
        batch_op.drop_column('eau_visé')
        batch_op.drop_column('eau_actuelle')
        batch_op.drop_column('eau_max')
        batch_op.drop_column('eau_min')
        batch_op.drop_column('gaz_visé')
        batch_op.drop_column('gaz_actuelle')
        batch_op.drop_column('gaz_max')
        batch_op.drop_column('gaz_min')

    # ### end Alembic commands ###
