"""ajout de houseid dans le type

Revision ID: 99e89f7c2353
Revises: ee69e881d2e1
Create Date: 2025-04-01 11:30:48.450974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e89f7c2353'
down_revision = 'ee69e881d2e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('object_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('house_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'houses', ['house_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('object_types', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('house_id')

    # ### end Alembic commands ###
