"""empty message

Revision ID: b4687373e081
Revises: 9a81722539e6
Create Date: 2025-04-09 21:16:59.788975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4687373e081'
down_revision = '9a81722539e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('default_object_parametre')
    op.drop_table('parametres')
    op.drop_table('rapports')
    op.drop_table('object_room_associations')
    with op.batch_alter_table('connected_objects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conso_visé', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('temp_min', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('temp_max', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('temp_actuelle', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('temp_visé', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('batterie', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connected_objects', schema=None) as batch_op:
        batch_op.drop_column('batterie')
        batch_op.drop_column('temp_visé')
        batch_op.drop_column('temp_actuelle')
        batch_op.drop_column('temp_max')
        batch_op.drop_column('temp_min')
        batch_op.drop_column('conso_visé')

    op.create_table('object_room_associations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('object_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['connected_objects.id'], name='object_room_associations_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='object_room_associations_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rapports',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('object_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('house_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contenu', mysql.TEXT(), nullable=False),
    sa.Column('date_creation', mysql.DATETIME(), nullable=True),
    sa.Column('date_maj', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name='rapports_ibfk_1'),
    sa.ForeignKeyConstraint(['object_id'], ['connected_objects.id'], name='rapports_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('parametres',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('object_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parametre', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('value', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('unite', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['connected_objects.id'], name='parametres_ibfk_1'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='parametres_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='parametres_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('default_object_parametre',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parametre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('default_value', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
