"""empty message

Revision ID: dccaa9204b8a
Revises: 87f7bcc2a751
Create Date: 2025-04-14 18:52:58.241513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dccaa9204b8a'
down_revision = '87f7bcc2a751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connected_objects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autre_min', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('autre_max', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('autre_actuelle', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('autre_visé', sa.Integer(), nullable=True))

    with op.batch_alter_table('object_types', schema=None) as batch_op:
        batch_op.drop_column('consumes_gas')
        batch_op.drop_column('consumes_water')
        batch_op.drop_column('other_consumption')
        batch_op.drop_column('consumes_electricity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('object_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consumes_electricity', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('other_consumption', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('consumes_water', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('consumes_gas', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    with op.batch_alter_table('connected_objects', schema=None) as batch_op:
        batch_op.drop_column('autre_visé')
        batch_op.drop_column('autre_actuelle')
        batch_op.drop_column('autre_max')
        batch_op.drop_column('autre_min')

    # ### end Alembic commands ###
